language: python

python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8

install:
  - pip install -U pip -r requirements.txt

script:
  - pytest.sh
  - codecov --file coverage/index.xml

notifications:
  email:
    recipients:
      - rugleb@gmail.com
    on_success: never
    on_failure: always
